[build]
builder = "NIXPACKS"
buildCommand = "cargo build --release"

[deploy]
startCommand = "./target/release/mnz-chain-rust"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
